bugzilla:
    url: "https://bugzilla.mozilla.org/rest/"
    creator: "infosec+rra2json@mozilla.com"
    rra:
        product: "Enterprise Information Security"
        component: "Rapid Risk Analysis"
        assignees:
            - jclaudius@mozilla.com
            - culucenk@mozilla.com
            - gdestuynder@mozilla.com
        cache: "/tmp/rra_assignees.pickle"
    va:
        product: "Enterprise Information Security"
        component: "Vulnerability Assessment"
        assignees:
            - jclaudius@mozilla.com
            - smacleod@mozilla.com
            - culucenk@mozilla.com
            - gdestuynder@mozilla.com
        cache: "/tmp/va_assignees.pickle"
casa:
    url: "https://biztera.com/api/v1/"
    lookup_period_in_days: 30
    bot_email: 'bizbot@biztera.com'
