bugzilla:
    url: "https://bugzilla.mozilla.org/rest/"
    creator: "infosec+rra2json@mozilla.com"
    needinfo: "jclaudius@mozilla.com"
    rra:
        product: "Enterprise Information Security"
        component: "Rapid Risk Analysis"
        assignees:
            - gene@mozilla.com
            - stephouillon@mozilla.com
        cache: "/tmp/rra_assignees.pickle"
    va:
        product: "Enterprise Information Security"
        component: "Vulnerability Assessment"
        assignees:
            - gene@mozilla.com
        cache: "/tmp/va_assignees.pickle"
casa:
    url: "https://biztera.com/api/v1/"
    lookup_period_in_days: 30
    bot_email: 'bizbot@biztera.com'
foxsec:
    assignees:
        - gene@mozilla.com
        - stephouillon@mozilla.com
    keywords:
        - fxa
        - firefox
        - balrog
        - normandy
        - telemetry
        - fxsend
        - fxmonitor
        - fpn
        - taskcluster
        - shipit
        - sentry
        - phabricator
        - lando
